name: Run Salesforce Tests

on: [pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Restore node_modules cache'
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ env.cache-name }}-
            npm-

      - name: 'Install npm dependencies'
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: 'Code formatting verification with Prettier'
        run: npm run prettier

      - name: Run Apex tests
        run: sfdx force:apex:test:run --resultformat junit --outputdir test-results/apex --codecoverage

      - name: 'Unit test Lightning Web Components'
        run: npm run test:unit:coverage

      - name: 'Install Salesforce CLI'
        run: |
          npm install sfdx-cli --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH
          sfdx --version
